markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
permalink: pretty
title: Blessed JavaScript
description: ğŸ™ Unofficial blessed libraries for common tasks in JavaScript
